### ISSUE TITLE
求一个基于 asciinema 的 demo

### ISSUE THREAD

**Issue by jizhilong** [MarchLiu/jouter#1]
> 在现代的命令行工具开发时， 我们经常会遇到子命令/选项间有非正交的相关关系，用.分割，以层级关系划分成树状结构，符合程序员的经验， 辅以Shell的命令行完成提示（shell command completion），无需记忆完整的路径，也无需查阅文档，即可 按 tab 键查找完成子命令输入。

这段文字描述的命令行参数设计范式很吸引人，如果能提供一个用 [ascinema](https://asciinema.org/) 等工具录制的动态 demo 就更好了。

**Comment by MarchLiu** [comment]
感谢您的建议，正好[pyouter](https://github.com/fanfeilong/task_router) 项目这几天在内部试用，我看看有没有合适的场景做一个。
pyouter和jouter遵循同样的设计，只是实现的语言不同

**Comment by MarchLiu** [comment]
今天用 pyouter 做了一个录屏，希望对您有帮助 ![pyouter](https://github.com/fanfeilong/task_router/blob/main/pyouter.gif) 。因为语言的限制，jouter 要做到同样的效果要麻烦很多，我正在想办法简化。

**Comment by jizhilong** [comment]
> 今天用 pyouter 做了一个录屏，希望对您有帮助 ![pyouter](https://github.com/fanfeilong/task_router/blob/main/pyouter.gif) 。因为语言的限制，jouter 要做到同样的效果要麻烦很多，我正在想办法简化。

谢谢。

结合 https://github.com/fanfeilong/task_router/tree/main/src/pyouter/bash 中的 completion script 的代码来看，似乎这个设计有两大优势： completion script 通用，开发者不需要为每个 cli 定制 completion 扩展；一致的层级式命令风格，已经有经验的用户学习成本低。我觉得这两个特点对于企业内的工具开发尤其适用，他们能像代码规范那样减少很多不必要的心智负担。
